CREATE TABLE products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    price NUMERIC(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    location_x INTEGER NOT NULL,
    location_y INTEGER NOT NULL
);


CREATE TABLE orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAIL'),
    order_timestamp TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_order
        FOREIGN KEY(order_id) 
        REFERENCES orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_product
        FOREIGN KEY(product_id) 
        REFERENCES products(id)
);

CREATE TABLE routes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_order
        FOREIGN KEY(order_id) 
        REFERENCES orders(id)
        ON DELETE CASCADE
);

CREATE TABLE route_locations (
    route_id BIGINT NOT NULL,
    location_x INTEGER NOT NULL,
    location_y INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    CONSTRAINT fk_route
        FOREIGN KEY(route_id) 
        REFERENCES routes(id)
        ON DELETE CASCADE,
    PRIMARY KEY (route_id, step_order)
);